service: Ec2Toggle
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  memorySize: 256
  logRetentionInDays: 5
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeRegions
        - ec2:DescribeInstances
        - ec2:StartInstances
        - ec2:StopInstances
      Resource: '*'

functions:
  ListInstances:
    handler: src/handler/ListInstances.handler
    events:
      - http:
          path: list-instances
          method: get
          cors: true

  StartOrStopAnInstance:
    handler: src/handler/StartOrStopAnInstance.handler
    events:
      - http:
          path: start-stop-instance
          method: post
          cors: true

  StopInstancesCron:
    handler: src/cron/StopInstances.handler
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-offline